# .github/workflows/ci-cd-pipeline.yml

# Name of the workflow (visible in GitHub Actions UI)
name: DevOps Meme/Quote Generator CI/CD Pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the main branch
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-test"
  build-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Example step: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # Example step: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Check if requirements.txt exists and install dependencies
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Example step: Run tests (placeholder)
      # You would add your actual test commands here
      - name: Run tests
        run: |
          echo "Running tests..."
          # python -m pytest # Example if you were using pytest
          # Add your test commands

      # --- Docker Steps ---
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub (or ECR)
        # Use a secret to store your Docker Hub/ECR credentials
        # This example assumes Docker Hub. Adjust for ECR if needed.
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # Set this secret in GitHub
          password: ${{ secrets.DOCKERHUB_TOKEN }}    # Set this secret in GitHub

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true # Push the image
          # Tag the image with the commit SHA for uniqueness
          tags: your-dockerhub-username/devops-meme-quote-generator:${{ github.sha }}
